import type { PresetId, Size } from './presets'
import type {
  GuideSettings,
  MediaType,
  PlacedMedia,
  Slide,
  TextStyleDefaults,
} from '../store/useTiovivoStore'
import { createZip, readZip } from './zip'

export const VPOST_FORMAT = 'vpost'
export const VPOST_VERSION = 1

export interface ProjectAsset {
  id: string
  name: string
  mime: string
  path: string
}

export interface ProjectManifest {
  format: typeof VPOST_FORMAT
  version: number
  app?: { name?: string; version?: string }
  dimensions: Size
  presetId: PresetId
  customWidth: number
  customHeight: number
  workspaceBgColor?: string
  slides: Slide[]
  assets: ProjectAsset[]
  items: (Omit<PlacedMedia, 'src' | 'coverImageSrc'> & {
    // Optional for text items, which carry no media asset
    assetId?: string
    coverAssetId?: string
  })[]
  // Workspace settings — guide visibility, snap toggles, and the
  // last-used text styling. All optional for backwards compatibility
  // with older .vpost files (the store keeps current values).
  guides?: Partial<GuideSettings>
  lastTextStyle?: Partial<TextStyleDefaults>
}

export interface SerializeInput {
  slides: Slide[]
  items: PlacedMedia[]
  dimensions: Size
  presetId: PresetId
  customWidth: number
  customHeight: number
  workspaceBgColor: string
  guides?: GuideSettings
  lastTextStyle?: TextStyleDefaults
  /** Optional "Fit view" snapshot embedded in the .vpost as preview.png.
   *  Generated by generateProjectPreview(). */
  preview?: Blob | null
}

function extFromMime(mime: string, fallback: string): string {
  if (mime === 'image/jpeg') return 'jpg'
  if (mime === 'image/png') return 'png'
  if (mime === 'image/gif') return 'gif'
  if (mime === 'image/webp') return 'webp'
  if (mime === 'video/mp4') return 'mp4'
  if (mime === 'video/quicktime') return 'mov'
  if (mime === 'video/webm') return 'webm'
  return fallback || 'bin'
}

function extFromName(name: string): string {
  const i = name.lastIndexOf('.')
  return i >= 0 ? name.slice(i + 1).toLowerCase() : ''
}

export async function serializeProject(
  state: SerializeInput,
  getAssetBlob: (src: string) => Promise<Blob>,
): Promise<Blob> {
  const srcToAsset = new Map<string, ProjectAsset>()
  const assetBlobs: { name: string; data: Blob }[] = []
  let counter = 0

  const registerAsset = async (src: string, displayName: string) => {
    if (srcToAsset.has(src)) return srcToAsset.get(src)!.id
    const blob = await getAssetBlob(src)
    const id = `a${++counter}`
    const ext = extFromMime(blob.type, extFromName(displayName))
    const path = `assets/${id}.${ext}`
    srcToAsset.set(src, { id, name: displayName, mime: blob.type, path })
    assetBlobs.push({ name: path, data: blob })
    return id
  }

  for (const item of state.items) {
    if (item.type === 'text') continue
    await registerAsset(item.src, item.name)
    if (item.coverImageSrc) {
      await registerAsset(item.coverImageSrc, `cover-${item.name}`)
    }
  }

  const manifest: ProjectManifest = {
    format: VPOST_FORMAT,
    version: VPOST_VERSION,
    dimensions: state.dimensions,
    presetId: state.presetId,
    customWidth: state.customWidth,
    customHeight: state.customHeight,
    workspaceBgColor: state.workspaceBgColor,
    guides: state.guides,
    lastTextStyle: state.lastTextStyle,
    slides: state.slides,
    assets: Array.from(srcToAsset.values()),
    items: state.items.map((it) => {
      const { src: _src, coverImageSrc: _cs, ...rest } = it
      void _src; void _cs
      const out: ProjectManifest['items'][number] = { ...rest }
      if (it.type !== 'text') {
        out.assetId = srcToAsset.get(it.src)!.id
        if (it.coverImageSrc) {
          out.coverAssetId = srcToAsset.get(it.coverImageSrc)!.id
        }
      }
      return out
    }),
  }

  const manifestBlob = new Blob([JSON.stringify(manifest, null, 2)], {
    type: 'application/json',
  })

  const extras: { name: string; data: Blob }[] = []
  if (state.preview) {
    extras.push({ name: 'preview.png', data: state.preview })
  }

  return createZip([
    { name: 'project.json', data: manifestBlob },
    ...assetBlobs,
    ...extras,
  ])
}

export interface DeserializedProject {
  manifest: ProjectManifest
  assetBlobs: Map<string, Blob>
}

export function deserializeProject(buffer: Uint8Array): DeserializedProject {
  const entries = readZip(buffer)
  const manifestEntry = entries.find((e) => e.name === 'project.json')
  if (!manifestEntry) throw new Error('Not a .vpost file: missing project.json')

  const text = new TextDecoder().decode(manifestEntry.data)
  let manifest: ProjectManifest
  try {
    manifest = JSON.parse(text)
  } catch {
    throw new Error('project.json is not valid JSON')
  }

  if (manifest.format !== VPOST_FORMAT) {
    throw new Error(`Unsupported file format: ${manifest.format}`)
  }
  if (typeof manifest.version !== 'number' || manifest.version > VPOST_VERSION) {
    throw new Error(`Unsupported project version: ${manifest.version}. This app supports up to v${VPOST_VERSION}.`)
  }

  const byPath = new Map(entries.map((e) => [e.name, e.data]))
  const assetBlobs = new Map<string, Blob>()
  for (const asset of manifest.assets) {
    const data = byPath.get(asset.path)
    if (!data) throw new Error(`Missing asset in archive: ${asset.path}`)
    assetBlobs.set(asset.id, new Blob([data as BlobPart], { type: asset.mime }))
  }

  return { manifest, assetBlobs }
}

export function hydrateItems(
  manifest: ProjectManifest,
  assetUrls: Map<string, string>,
): PlacedMedia[] {
  return manifest.items.map((it) => {
    const { assetId, coverAssetId, ...rest } = it
    if (rest.type === 'text') {
      return { ...rest, src: '', type: 'text' as MediaType }
    }
    if (!assetId) throw new Error('Media item missing assetId')
    const url = assetUrls.get(assetId)
    if (!url) throw new Error(`No URL for assetId ${assetId}`)
    const hydrated: PlacedMedia = { ...rest, src: url, type: rest.type as MediaType }
    if (coverAssetId) {
      const coverUrl = assetUrls.get(coverAssetId)
      if (coverUrl) hydrated.coverImageSrc = coverUrl
    }
    return hydrated
  })
}
